# Comment to a new PR.
pullRequestOpened: >
  :sparkling_heart: Thank you so much for creating the pull request! :sparkling_heart:

  Have a look at [the test workflow](https://github.com/OrkoHunter/pep8speaks/blob/master/tests/test_workflow.py). The branch of this pull request is going to be deployed on Heroku with payload URL https://pep8speaks-pr-xxx.herokuapp.com . The repository https://github.com/OrkoHunter/test-pep8speaks is configured to test review deployments like this.

  @OrkoHunter Please follow these steps to test this PR and deploy a new version!

  - Create a review app for this PR on [Heroku](https://dashboard.heroku.com/).
  - Update the `Webhook URL` of the [test-pep8speaks app](https://github.com/settings/apps/test-pep8speaks).
  - In [CircleCI](https://app.circleci.com/pipelines/github/OrkoHunter/pep8speaks) advanced settings, turn on the `Pass secrets to builds from forked pull requests`.
  - Restart the Pull Request build-and-test pipeline to test this PR. (PR can be merged if this passes).
  - Revert the Webhook URL of the test GitHub app when the Pull Request is merged.
  - Switch off the `Pass secrets to builds from forked pull requests` in the [CI](https://app.circleci.com/pipelines/github/OrkoHunter/pep8speaks) advanced settings.
  - Remember to make a new release if needed and deploy the production app.
