sudo: false

language: python

python:
  - 3.7

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -r requirements/test.txt

script:
  - echo "Make sure you the review app of this branch is deployed and configured in the test-pep8speaks app"
  - pytest

notifications:
  email: false
